# Generated by Django 3.2 on 2021-05-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='organization',
            field=models.IntegerField(default=0),
        ),
    ]
