# Generated by Django 3.2 on 2021-05-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='users',
            field=models.ManyToManyField(through='events.EventUserMappings', to='events.Users'),
        ),
    ]
