# Generated by Django 3.2 on 2021-05-03 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_users_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='users',
        ),
        migrations.AddField(
            model_name='users',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.events'),
        ),
        migrations.DeleteModel(
            name='EventUserMappings',
        ),
    ]
