repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        stages: [ commit ]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: master
    hooks:
      - id: commitizen
        stages: [ commit-msg ]